INSERT INTO drinks (name, source, ingredients, recipe, blurb) VALUES ('Tonberry', 'Final Fantasy', '.5 oz Midori (or other melon liqueur),
.5 oz Sour Apple Pucker,
.5 oz Absinthe',
'Mix all three ingredients in a shot glass and drink.',
'If you start seeing little green creatures with lanterns and knives, run away!'),
('Shoryuken', 'Street Fighter', '1 oz Southern Comfort,
 .25 oz Kahlua,
 .25 oz grenadine',
 'Mix the ingredients in a shot glass, pouring the Southern Comfort over the top last.  Mash buttons and drink.',
 'A drink that will probably not make you feel invincible when you wake up.'),
('The Kirby', 'Kirby', '1 cherry jello shot made with Malibu Coconut Rum,
 4 oz. pink lemonade,
 2 oz. Bacardi Superior Rum,
 1 oz. Hiram Walker Blackberry Brandy',
 ' Place the jello shot in the bottom of the glass first.  Slowly pour in pink lemonade, rum, and brandy.  If done properly, the jello shot will stay at the bottom of the glass.  Drink the alcohol and eat the jello shot last.',
 'The jello shot, according to drink’s creator Shana, absorbs the alcohol in the drink, just as Kirby absorbs his enemies powers!')
